WORD_QUERY = "SELECT w.dictid, w.word, w.meaning, uw.count, uw.like, uw.created_time, uw.id FROM `UserWord` uw LEFT JOIN `Word` w ON uw.wordid = w.id WHERE uw.userid = (SELECT id FROM `User` WHERE userid='%s');"
SENTENCE_QUERY = "SELECT s.raw, s.translated, s.like, s.updated_time, s.id FROM `Sentence` s where s.userid = (SELECT id FROM `User` WHERE userid='%s');"
NO_MEANING_WORDS_QUERY = "SELECT word FROM `Word` WHERE `meaning` is NULL"
UPDATE_MEANING_QUERY = "UPDATE `Word` set `meaning`=%s WHERE `word`=%s"
INSERT_SENTENCE_QUERY="INSERT INTO `Sentence` (`userid`, `raw`, `translated`) VALUES ((SELECT id FROM `User` WHERE userid='%s'), '%s', '%s');"
INSERT_WORD_QUERY = "INSERT INTO `Word`(`word`, `dictid`) VALUES ('%s', '%s')"
INSERT_USERWORD_QUERY = "INSERT INTO `UserWord`(`userid`, `wordid`) VALUES ((SELECT id FROM `User` WHERE userid='%s'), %s)"
DELETE_SENTENCE_QUERY="DELETE FROM `Sentence` WHERE `id`=%s;"
DELETE_WORD_QUERY="DELETE FROM `UserWord` WHERE `id`=%s;"
SELECT_WORD_QUERY = "SELECT id FROM `Word` WHERE `word`='%s'"